DROP DATABASE IF EXISTS GROCERY_DB;

CREATE DATABASE GROCERY_DB;

\C GROCERY_DB;

CREATE TABLE PRODUCTS (
  ID INTEGER NOT NULL,
  PRODUCT_NAME VARCHAR(30) NOT NULL,
  CATEGORY_NAME VARCHAR(30) NOT NULL
);

PRODUCTS