3.-- Create a new database

DROP DATABASE IF EXISTS UNIVERSITY;

CREATE DATABASE UNIVERSITY;

\C UNIVERSITY;

-- Create a students table
CREATE TABLE STUDENTS (
    STUDENT_ID INTEGER PRIMARY KEY,
    STUDENT_NAME VARCHAR(255)
);

-- Create a courses table
CREATE TABLE COURSES (
    COURSE_ID INTEGER PRIMARY KEY,
    COURSE_NAME VARCHAR(255)
);

-- Create an enrollments table
CREATE TABLE ENROLLMENTS (
    ENROLLMENT_ID INTEGER PRIMARY KEY,
    STUDENT_ID INTEGER,
    COURSE_ID INTEGER,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);