-- Write your Schema Here --
DROP DATABASE IF EXISTS GROCERY_DB;

CREATE DATABASE GROCERY_DB;

\C GROCERY_DB;

CREATE TABLE CUSTOMERS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30)
);

CREATE TABLE CUSTOMER_ORDERS (
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    ORDER_DETAILS TEXT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCE CUSTOMER(ID) ON DELETE SET NULL
);