DROP DATABASE IF EXISTS COMPANY;

CREATE DATABASE COMPANY;

\C COMPANY;

-- CONVERT THE FOLLOWING INTO 3RD NORMAL FORM STANDARDIZATION --
CREATE TABLE BUSINESSES (
    BUSINESS_ID INTEGER PRIMARY KEY,
    BUSINESS_NAME VARCHAR(255),
);

CREATE TABLE LOCATION (
    LOCATION_ID INTEGER PRIMARY KEY LOCATION_NAME VARCHAR(255),
    LOCATION_MANAGER VARCHAR(255),
    CREATE TABLE LB_MAP ( ID INTEGER PRIMARY KEY, BUSINESS_ID INTEGER, LOCATION_ID INTEGER, FOREIGN KEY (BUSINESS_ID) REFERENCES STUDENTS(BUSINESS_ID), FOREIGN KEY (LOCATION_ID INTEGER, ) REFERENCES COURSES(LOCATION_ID );

// get code from gitlab

)