DROP DATABASE IF EXISTS CUSTOMER_DB;

CREATE DATABASE CUSTOMER_DB;

\C CUSTOMER_DB;

CREATE TABLE CUSTOMERS (
  ID INTEGER NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  VALUE_CARD_MEMBER BOOLEAN NOT NULL
);